In [26]:
from pynq import Overlay
ol = Overlay('matrix1.bit')

In [2]:
ol?

In [27]:
dma = ol.axi_dma_0

In [4]:
dma?

In [28]:
data_send = dma.sendchannel
data_recv = dma.recvchannel

In [29]:
import numpy as np
import matplotlib as plt
import random

In [30]:
MAT_SIZE = 8
data_A = np.random.randint(low=0, high=10, size=(8, 8)).astype(np.float32)
data_B = np.random.randint(low=0, high=10, size=(8, 8)).astype(np.float32)

In [31]:
data_A

array([[0., 3., 6., 8., 6., 1., 6., 2.],
       [2., 5., 5., 5., 1., 2., 4., 4.],
       [2., 5., 5., 9., 4., 6., 6., 7.],
       [1., 3., 3., 7., 0., 4., 3., 1.],
       [2., 2., 5., 2., 7., 1., 9., 0.],
       [0., 8., 9., 0., 9., 2., 9., 0.],
       [3., 7., 0., 6., 3., 4., 1., 7.],
       [2., 2., 7., 4., 4., 9., 4., 1.]], dtype=float32)

In [32]:
data_B

array([[7., 7., 1., 5., 2., 8., 0., 2.],
       [8., 4., 0., 6., 9., 1., 1., 0.],
       [5., 6., 9., 6., 3., 8., 7., 2.],
       [9., 4., 3., 3., 2., 5., 8., 5.],
       [4., 2., 0., 6., 9., 0., 2., 1.],
       [8., 1., 8., 7., 6., 7., 4., 9.],
       [5., 1., 0., 1., 3., 1., 6., 1.],
       [9., 6., 2., 0., 7., 7., 0., 4.]], dtype=float32)

In [37]:
%%time
np.dot(data_A, data_B) #software

CPU times: user 922 µs, sys: 66 µs, total: 988 µs
Wall time: 796 µs


array([[206., 111.,  90., 127., 153., 118., 161.,  81.],
       [200., 116.,  86., 109., 135., 132., 114.,  78.],
       [317., 162., 136., 169., 221., 203., 180., 151.],
       [165.,  78.,  83.,  93.,  92., 108., 114.,  86.],
       [154.,  84.,  61., 116., 137.,  84., 125.,  49.],
       [206., 115.,  97., 179., 219., 103., 151.,  54.],
       [243., 126.,  67., 122., 184., 139.,  83., 104.],
       [218., 107., 151., 167., 160., 168., 151., 131.]], dtype=float32)

In [38]:
from pynq import allocate

In [10]:
allocate?

In [39]:
#combining inputs for buffer 
data_a_f = data_A.flatten()
data_b_f = data_B.flatten()

data_input = np.concatenate([data_a_f, data_b_f])

In [40]:
data_A

array([[0., 3., 6., 8., 6., 1., 6., 2.],
       [2., 5., 5., 5., 1., 2., 4., 4.],
       [2., 5., 5., 9., 4., 6., 6., 7.],
       [1., 3., 3., 7., 0., 4., 3., 1.],
       [2., 2., 5., 2., 7., 1., 9., 0.],
       [0., 8., 9., 0., 9., 2., 9., 0.],
       [3., 7., 0., 6., 3., 4., 1., 7.],
       [2., 2., 7., 4., 4., 9., 4., 1.]], dtype=float32)

In [41]:
data_a_f

array([0., 3., 6., 8., 6., 1., 6., 2., 2., 5., 5., 5., 1., 2., 4., 4., 2.,
       5., 5., 9., 4., 6., 6., 7., 1., 3., 3., 7., 0., 4., 3., 1., 2., 2.,
       5., 2., 7., 1., 9., 0., 0., 8., 9., 0., 9., 2., 9., 0., 3., 7., 0.,
       6., 3., 4., 1., 7., 2., 2., 7., 4., 4., 9., 4., 1.], dtype=float32)

In [42]:
data_B

array([[7., 7., 1., 5., 2., 8., 0., 2.],
       [8., 4., 0., 6., 9., 1., 1., 0.],
       [5., 6., 9., 6., 3., 8., 7., 2.],
       [9., 4., 3., 3., 2., 5., 8., 5.],
       [4., 2., 0., 6., 9., 0., 2., 1.],
       [8., 1., 8., 7., 6., 7., 4., 9.],
       [5., 1., 0., 1., 3., 1., 6., 1.],
       [9., 6., 2., 0., 7., 7., 0., 4.]], dtype=float32)

In [43]:
data_b_f

array([7., 7., 1., 5., 2., 8., 0., 2., 8., 4., 0., 6., 9., 1., 1., 0., 5.,
       6., 9., 6., 3., 8., 7., 2., 9., 4., 3., 3., 2., 5., 8., 5., 4., 2.,
       0., 6., 9., 0., 2., 1., 8., 1., 8., 7., 6., 7., 4., 9., 5., 1., 0.,
       1., 3., 1., 6., 1., 9., 6., 2., 0., 7., 7., 0., 4.], dtype=float32)

In [44]:
data_input

array([0., 3., 6., 8., 6., 1., 6., 2., 2., 5., 5., 5., 1., 2., 4., 4., 2.,
       5., 5., 9., 4., 6., 6., 7., 1., 3., 3., 7., 0., 4., 3., 1., 2., 2.,
       5., 2., 7., 1., 9., 0., 0., 8., 9., 0., 9., 2., 9., 0., 3., 7., 0.,
       6., 3., 4., 1., 7., 2., 2., 7., 4., 4., 9., 4., 1., 7., 7., 1., 5.,
       2., 8., 0., 2., 8., 4., 0., 6., 9., 1., 1., 0., 5., 6., 9., 6., 3.,
       8., 7., 2., 9., 4., 3., 3., 2., 5., 8., 5., 4., 2., 0., 6., 9., 0.,
       2., 1., 8., 1., 8., 7., 6., 7., 4., 9., 5., 1., 0., 1., 3., 1., 6.,
       1., 9., 6., 2., 0., 7., 7., 0., 4.], dtype=float32)

In [45]:
input_buffer = allocate(128, np.float32)
output_buffer = allocate((8,8), np.float32)

In [46]:
np.copyto(input_buffer, data_input)

In [62]:
%%time 
data_send.transfer(input_buffer)
data_recv.transfer(output_buffer)
data_send.wait()
data_recv.wait()

CPU times: user 690 µs, sys: 55 µs, total: 745 µs
Wall time: 795 µs


In [60]:
output_buffer

PynqBuffer([[206., 111.,  90., 127., 153., 118., 161.,  81.],
            [200., 116.,  86., 109., 135., 132., 114.,  78.],
            [317., 162., 136., 169., 221., 203., 180., 151.],
            [165.,  78.,  83.,  93.,  92., 108., 114.,  86.],
            [154.,  84.,  61., 116., 137.,  84., 125.,  49.],
            [206., 115.,  97., 179., 219., 103., 151.,  54.],
            [243., 126.,  67., 122., 184., 139.,  83., 104.],
            [218., 107., 151., 167., 160., 168., 151., 131.]],
           dtype=float32)

In [49]:
input_buffer

PynqBuffer([0., 3., 6., 8., 6., 1., 6., 2., 2., 5., 5., 5., 1., 2., 4.,
            4., 2., 5., 5., 9., 4., 6., 6., 7., 1., 3., 3., 7., 0., 4.,
            3., 1., 2., 2., 5., 2., 7., 1., 9., 0., 0., 8., 9., 0., 9.,
            2., 9., 0., 3., 7., 0., 6., 3., 4., 1., 7., 2., 2., 7., 4.,
            4., 9., 4., 1., 7., 7., 1., 5., 2., 8., 0., 2., 8., 4., 0.,
            6., 9., 1., 1., 0., 5., 6., 9., 6., 3., 8., 7., 2., 9., 4.,
            3., 3., 2., 5., 8., 5., 4., 2., 0., 6., 9., 0., 2., 1., 8.,
            1., 8., 7., 6., 7., 4., 9., 5., 1., 0., 1., 3., 1., 6., 1.,
            9., 6., 2., 0., 7., 7., 0., 4.], dtype=float32)

In [50]:
np.dot(data_A, data_B) - output_buffer

PynqBuffer([[0., 0., 0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)